name: Tests

on:
    push:
    pull_request:
        branches: [ main ]

jobs:
    run_unit_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: python3 -m unittest discover -s test/unit -p "test_*.py" -v

    run_func_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash test/func/test_print_fires.sh

    run_linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install pycodestyle
            - run: pycodestyle $(git ls-files '*.py')